CREATE DATABASE python_project;
USE python_project;
select * from sales_data;

--Q1. What is the total revenue generated by male vs. female customers?
select gender,sum(purchase_amount) as revenue
from sales_data
group by gender;

--Q2.Which customers used a discount but still spent more than the average purchase amount? 
select customer_id,purchase_amount
from sales_data
where discount_applied ="yes" and purchase_amount >= (select avg(purchase_amount) from sales_data);

--Q3.Which are the top 5 products with the highest average review rating?
SELECT item_purchased,
       ROUND(AVG(review_rating), 2) AS avg_product_rating
FROM sales_data
GROUP BY item_purchased
ORDER BY avg_product_rating DESC
LIMIT 5;

--Q4 Compare the average Purchase Amounts between Standard and Express Shipping.
select shipping_type, 
ROUND(AVG(purchase_amount),2)
from sales_data
where shipping_type in ('Standard','Express')
group by shipping_type;

--Q5 Do subscribed customers spend more? Compare average spend and total revenue 
--between subscribers and non-subscribers.
select subscription_status,
count(customer_id) as total_customer,
round(avg(purchase_amount),2) as avg_spend,
round(sum(purchase_amount),2) as total_revenue
from sales_data
group by subscription_status
order by total_revenue,avg_spend desc;

--Q6. Which 5 products have the highest percentage of purchases with discounts applied?
SELECT item_purchased,
       ROUND(100.0 * AVG(discount_applied = 'Yes'), 2) AS discount_rate
FROM sales_data
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5;

--Q7. Segment customers into New, Returning, and Loyal based on their total number of previous purchases, and show the count of each segment.

SELECT
    SUM(CASE WHEN previous_purchases = 1 THEN 1 ELSE 0 END) AS new_customers,
    SUM(CASE WHEN previous_purchases BETWEEN 2 AND 10 THEN 1 ELSE 0 END) AS returning_customers,
    SUM(CASE WHEN previous_purchases > 10 THEN 1 ELSE 0 END) AS loyal_customers
FROM sales_data;

--Q8.What are the top 3 most purchased products within each category? 
WITH item_counts AS (
    SELECT category,
           item_purchased,
           COUNT(customer_id) AS total_orders,
           ROW_NUMBER() OVER (
               PARTITION BY category
               ORDER BY COUNT(customer_id) DESC
           ) AS item_rank
    FROM sales_data
    GROUP BY category, item_purchased
)
SELECT item_rank,
       category,
       item_purchased,
       total_orders
FROM item_counts
WHERE item_rank <= 3;

--Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
SELECT subscription_status,
       COUNT(customer_id) AS repeat_buyers
FROM sales_data
WHERE previous_purchases > 5
GROUP BY subscription_status;

--Q10.What is the revenue contribution of each age group? 
SELECT 
    age_group,
    SUM(purchase_amount) AS total_revenue
FROM sales_data
GROUP BY age_group
ORDER BY total_revenue desc;

